sudo: required
language: bash
services:
  - docker
before_script:
  - docker-compose build r-luckyguess
script: docker-compose run --rm --entrypoint sh -e KBC_TOKEN=$KBC_TOKEN r-luckyguess /code/docker/run_tests.sh
after_success:
  - docker images
deploy:
  provider: script
  skip_cleanup: true
  script: ./docker/deploy.sh
  on:
    tags: true  

notifications:
  slack:  
    secure: W1vQTOoJLHbyoKgrtM5MaC2DVv+2GcDn/lPyS32z2lCykrmFTBNlI4eMo+sEAv9t+oEc3vUO0uWxYFRXNISqMq5P5cyn6o6OArzRrc5Mn5KrIbM8A5AzCUyTa7ba3W5vPPRmkfRvIAHjbfBLO0vNM0NsmZy/cgiovLc9e84+dsNnkL2LATXPTybMQ9IOuOKvOrDZ1YqBd4AoJg2ePXrf0pVuLiqocvcqv3pzwWYVpX269BoVLjKNg8wA00Jb2SvE1DKjeJfAPx61EEmS4Eqoy0aCyqzxervD1HEVs/ukc7ksuSIJHQSezs0iQGMJEdVkJyQWPzyJgX5XiAlDaRfmADbsup06REkOAJOTRxWd5ouoU534NvWFOQTL6g33LeVOhhC4SCk18hTBaMoyMSXHPc45ugNEQL9KT7f5VGuiVVwmX9ZNSXvSMPtuX02LXvLI5sg5RvGT0rFPzv6rVuN5dEsqozEXSArZs1v5P1McCbNASxDatLO3wrHX8yIkj2EYEzjwlMWTL2CSyYY/t5B48zM4NQBon1+clrrUKq36/3PCIZ8alWhRv6rqso7H68AYwoNc5IJUKpW8z13i10s1aWh/2kE1ZoI8Bdlf2k2C55Wnq14kxC+Fu90NNM2PSVWuCU+kgTUidKFuc8IHowTUfovXc7sTlA0rqhNPo4ot3pA=
  email: false
